module.exports = (sequelize, Sequelize) => {
  return sequelize.define("product", {
    ID:               {type: Sequelize.BIGINT,      allowNull: false, primaryKey: true, autoIncrement: true},
    foreignID:        {type: Sequelize.STRING(200), allowNull: true},
    sourceProductID:  {type: Sequelize.BIGINT,      allowNull: true},
    accountID:        {type: Sequelize.BIGINT,      allowNull: true},
    eanCode:          {type: Sequelize.STRING(200), allowNull: true},
    code:             {type: Sequelize.STRING(200), allowNull: false},
    title:            {type: Sequelize.STRING(200), allowNull: false},
    description:      {type: Sequelize.STRING(10000), allowNull: true, defaultValue: null},
    height:           {type: Sequelize.DECIMAL(10,3), allowNull: true},
    width:            {type: Sequelize.DECIMAL(10,3), allowNull: true},
    depth:            {type: Sequelize.DECIMAL(10,3), allowNull: true},
    volume:           {type: Sequelize.DECIMAL(10,3), allowNull: false},
    weight:           {type: Sequelize.DECIMAL(10,3), allowNull: false},
    pieces:           {type: Sequelize.INTEGER,     allowNull: false},
    categoryID:       {type: Sequelize.BIGINT,      allowNull: false},
    lacedID:          {type: Sequelize.BIGINT,      allowNull: true},
    lacedTitle:            {type: Sequelize.STRING(200), allowNull: true},
    lacedCode:            {type: Sequelize.STRING(200), allowNull: true},
    public:           {type: Sequelize.BOOLEAN,     allowNull: false, defaultValue: 0},
    untracked:        {type: Sequelize.BOOLEAN,     allowNull: false, defaultValue: 0},
    imageReference:   {type: Sequelize.STRING(1000), allowNull: true},
    stockxId:         {type: Sequelize.STRING(100),  allowNull: true},
    status:           {type: Sequelize.STRING(100),  allowNull: false, defaultValue: 'active'},
    category2:                           {type: Sequelize.STRING(500), allowNull: true},
    gender:                              {type: Sequelize.STRING(200), allowNull: true},
    color:                               {type: Sequelize.STRING(300), allowNull: true},
    retailPrice:                         {type: Sequelize.DECIMAL(10,2), allowNull: true},
    releaseDate:                         {type: Sequelize.DATEONLY,     allowNull: true},
    brand:                               {type: Sequelize.STRING(200),  allowNull: true},
    salesLast72Hours:                    {type: Sequelize.INTEGER,  allowNull: true},
    salesLast72HoursChangePercentage:    {type: Sequelize.INTEGER,  allowNull: true},
    lastSalePrice:                       {type: Sequelize.FLOAT(10,2),  allowNull: true},
    lastSaleChangePercentage:            {type: Sequelize.FLOAT(10,2),  allowNull: true},
    volatilityScore:                     {type: Sequelize.FLOAT(10,2),  allowNull: true},
    volatilityScoreChangePercentage:     {type: Sequelize.FLOAT(10,2),  allowNull: true},
    // lacedProductID:                      {type: Sequelize.BIGINT,      allowNull: true},
  });
};
