steps:
# Load Dockerfile
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$_BUCKET/microservices/email/production.dockerfile', 'Dockerfile']

# Load gc-auths
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$_BUCKET/wiredhub.storage.admin.auths.json', 'wiredhub.storage.admin.auths.json']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wiredhub/production-email', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wiredhub/production-email']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'production-email', '--image', 'gcr.io/wiredhub/production-email', '--region', 'europe-west2', '--platform', 'managed', '--timeout', '899']

images:
- gcr.io/wiredhub/production-email
